@startuml

title __NETWORK's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.DelayMatrix_Float {
            # mDelayMatrix : float[][]
            # mTotalNodeNum : int
            + DelayMatrix_Float()
            + getDelay()
            + toString()
            - DelayMatrix_Float()
            - calculateShortestPath()
            - createDelayMatrix()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.FloydWarshall_Float {
            - Dk : float[][]
            - Dk_minus_one : float[][]
            - Pk : int[][]
            - Pk_minus_one : int[][]
            - numVertices : int
            + allPairsShortestPaths()
            + getPK()
            + initialize()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.GraphReaderBrite {
            {static} - PARSE_EDGES : int
            {static} - PARSE_NODES : int
            {static} - PARSE_NOTHING : int
            - state : int
            + readGraphFile()
            - parseEdgesString()
            - parseNodeString()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        interface org.cloudbus.cloudsim.network.GraphReaderIF {
            {abstract} + readGraphFile()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.TopologicalGraph {
            - linkList : List<TopologicalLink>
            - nodeList : List<TopologicalNode>
            + TopologicalGraph()
            + addLink()
            + addNode()
            + getLinkIterator()
            + getNodeIterator()
            + getNumberOfLinks()
            + getNumberOfNodes()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.TopologicalLink {
            - destNodeID : int
            - linkBw : float
            - linkDelay : float
            - srcNodeID : int
            + TopologicalLink()
            + getDestNodeID()
            + getLinkBw()
            + getLinkDelay()
            + getSrcNodeID()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace network {
        class org.cloudbus.cloudsim.network.TopologicalNode {
            - nodeID : int
            - nodeName : String
            - worldX : int
            - worldY : int
            + TopologicalNode()
            + TopologicalNode()
            + TopologicalNode()
            + getCoordinateX()
            + getCoordinateY()
            + getNodeID()
            + getNodeLabel()
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.network.GraphReaderBrite .up.|> org.cloudbus.cloudsim.network.GraphReaderIF
  org.cloudbus.cloudsim.network.GraphReaderBrite o-- org.cloudbus.cloudsim.network.TopologicalGraph : graph


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
