@startuml

title __UTIL's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.Check {
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.ExecutionTimeMeasurer {
            {static} - executionTimes : Map<String, Long>
            {static} + end()
            {static} + getExecutionTimes()
            {static} + start()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.MathUtil {
            {static} + abs()
            {static} + countNonZeroBeginning()
            {static} + countShortestRow()
            {static} + createLinearRegression()
            {static} + createLinearRegression()
            {static} + createWeigthedLinearRegression()
            {static} + getLoessParameterEstimates()
            {static} + getRobustLoessParameterEstimates()
            {static} + getStatistics()
            {static} + getStatistics()
            {static} + getTricubeBisquareWeigts()
            {static} + getTricubeWeigts()
            {static} + iqr()
            {static} + listToArray()
            {static} + mad()
            {static} + mean()
            {static} + median()
            {static} + median()
            {static} + stDev()
            {static} + sum()
            {static} + trimZeroTail()
            {static} + variance()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.Test {
            + i1 : int
            + s1 : String
            + Test()
            + equals()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.Test2 {
            + st : String
            + Test2()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        class org.cloudbus.cloudsim.util.WorkloadFileReader {
            - COMMENT : String
            - GROUP_ID : int
            {static} - IRRELEVANT : int
            - JOB_NUM : int
            - MAX_FIELD : int
            - NUM_PROC : int
            - REQ_NUM_PROC : int
            - REQ_RUN_TIME : int
            - RUN_TIME : int
            - SUBMIT_TIME : int
            - USER_ID : int
            - fieldArray : String[]
            - file : File
            - jobs : ArrayList<Cloudlet>
            - rating : int
            + WorkloadFileReader()
            + generateWorkload()
            + setComment()
            + setField()
            - createJob()
            - extractField()
            - parseValue()
            - readFile()
            - readGZIPFile()
            - readZipFile()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace util {
        interface org.cloudbus.cloudsim.util.WorkloadModel {
            {abstract} + generateWorkload()
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.util.Test2 o-- org.cloudbus.cloudsim.util.Test : t
  org.cloudbus.cloudsim.util.WorkloadFileReader .up.|> org.cloudbus.cloudsim.util.WorkloadModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
