@startuml

title __PREDICATES's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          abstract class org.cloudbus.cloudsim.core.predicates.Predicate {
              {abstract} + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateAny {
              + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateFrom {
              - ids : int[]
              + PredicateFrom()
              + PredicateFrom()
              + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateNone {
              + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateNotFrom {
              - ids : int[]
              + PredicateNotFrom()
              + PredicateNotFrom()
              + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateNotType {
              - tags : int[]
              + PredicateNotType()
              + PredicateNotType()
              + match()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace core {
        namespace predicates {
          class org.cloudbus.cloudsim.core.predicates.PredicateType {
              - tags : int[]
              + PredicateType()
              + PredicateType()
              + match()
          }
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.core.predicates.PredicateAny -up-|> org.cloudbus.cloudsim.core.predicates.Predicate
  org.cloudbus.cloudsim.core.predicates.PredicateFrom -up-|> org.cloudbus.cloudsim.core.predicates.Predicate
  org.cloudbus.cloudsim.core.predicates.PredicateNone -up-|> org.cloudbus.cloudsim.core.predicates.Predicate
  org.cloudbus.cloudsim.core.predicates.PredicateNotFrom -up-|> org.cloudbus.cloudsim.core.predicates.Predicate
  org.cloudbus.cloudsim.core.predicates.PredicateNotType -up-|> org.cloudbus.cloudsim.core.predicates.Predicate
  org.cloudbus.cloudsim.core.predicates.PredicateType -up-|> org.cloudbus.cloudsim.core.predicates.Predicate


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
