@startuml

title __LISTS's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace lists {
        class org.cloudbus.cloudsim.lists.CloudletList {
            {static} + getById()
            {static} + getPositionById()
            {static} + sort()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace lists {
        class org.cloudbus.cloudsim.lists.HostList {
            {static} + getById()
            {static} + getHostWithFreePe()
            {static} + getHostWithFreePe()
            {static} + getNumberOfBusyPes()
            {static} + getNumberOfFreePes()
            {static} + getNumberOfPes()
            {static} + setPeStatus()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace lists {
        class org.cloudbus.cloudsim.lists.PeList {
            {static} + getById()
            {static} + getFreePe()
            {static} + getMaxUtilization()
            {static} + getMaxUtilizationAmongVmsPes()
            {static} + getMips()
            {static} + getNumberOfBusyPes()
            {static} + getNumberOfFreePes()
            {static} + getTotalMips()
            {static} + setPeStatus()
            {static} + setStatusFailed()
            {static} + setStatusFailed()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace lists {
        class org.cloudbus.cloudsim.lists.ResCloudletList {
            {static} + getByIdAndUserId()
            {static} + getPositionById()
            {static} + indexOf()
            {static} + move()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace lists {
        class org.cloudbus.cloudsim.lists.VmList {
            {static} + getById()
            {static} + getByIdAndUserId()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
