@startuml

title __REQUEST's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace request {
          class org.cloudbus.cloudsim.sdn.request.VMRequestGenerator {
              ~ vmId : int
              {static} - seed : long
              + generateLinks()
              + generateVM()
              + generateVM()
              + generateVMGroup()
              + generateVMs()
              {static} + main()
              {static} + round()
              + wrtieJSON()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace request {
          class org.cloudbus.cloudsim.sdn.request.VMRequestGenerator.LinkSpec {
              ~ bw : Long
              ~ destination : String
              ~ name : String
              ~ source : String
              + LinkSpec()
              ~ toJSON()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace request {
          class org.cloudbus.cloudsim.sdn.request.VMRequestGenerator.VMSpec {
              ~ bw : long
              ~ endtime : double
              ~ mips : long
              ~ name : String
              ~ pe : int
              ~ ram : int
              ~ size : long
              ~ starttime : double
              ~ type : String
              ~ toJSON()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace request {
          enum VMtype {
            AppServer
            DBServer
            Firewall
            Proxy
            WebServer
          }
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.sdn.request.VMRequestGenerator +-down- org.cloudbus.cloudsim.sdn.request.VMRequestGenerator.LinkSpec
  org.cloudbus.cloudsim.sdn.request.VMRequestGenerator +-down- org.cloudbus.cloudsim.sdn.request.VMRequestGenerator.VMSpec
  org.cloudbus.cloudsim.sdn.request.VMRequestGenerator +-down- org.cloudbus.cloudsim.sdn.request.VMRequestGenerator.VMtype


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
