@startuml

title __CONSTANTS's Class Diagram__\n

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.Directions {
            {static} + EAST : int
            {static} + NONE : int
            {static} + NORTH : int
            {static} + NORTHEAST : int
            {static} + NORTHWEST : int
            {static} + SOUTH : int
            {static} + SOUTHEAST : int
            {static} + SOUTHWEST : int
            {static} + WEST : int
        }
      }
    }
  }
  

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.Edge {
            {static} + BOTTOM : int
            {static} + LEFT : int
            {static} + NONE : int
            {static} + RIGHT : int
            {static} + UPON : int
        }
      }
    }
  }
  

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.MaxAndMin {
            {static} + AP_COVERAGE : int
            {static} + CLOUDLET_COVERAGE : int
            {static} + DELAY_PROCESS : int
            {static} + LIVE_MIG_POINT : int
            {static} + MAX_AP_DEVICE : int
            {static} + MAX_BANDWIDTH : int
            {static} + MAX_DIRECTION : int
            {static} + MAX_DISTANCE_TO_HANDOFF : int
            {static} + MAX_HANDOFF_TIME : int
            {static} + MAX_SERVER_CLOUDLET : int
            {static} + MAX_SERVICES : int
            {static} + MAX_SIMULATION_TIME : int
            {static} + MAX_SMART_THING : int
            {static} + MAX_SPEED : int
            {static} + MAX_ST_IN_AP : int
            {static} + MAX_VALUE_AGREE : float
            {static} + MAX_VALUE_SERVICE : float
            {static} + MAX_VM_SIZE : int
            {static} + MAX_X : int
            {static} + MAX_Y : int
            {static} + MIG_POINT : int
            {static} + MIN_BANDWIDTH : int
            {static} + MIN_HANDOFF_TIME : int
            {static} + MIN_VM_SIZE : int
            {static} + PROCESS_CONTAINER : double
            {static} + SIZE_CONTAINER : double
        }
      }
    }
  }
  

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.MobileEvents {
            {static} + ABORT_MIGRATION : int
            {static} + ADD_VM_NEW_CLOUDLET : int
            {static} + APP_SUBMIT_MIGRATE : int
            {static} + CHECK_NEW_STEP : int
            {static} + CONNECT_ST_TO_SC : int
            {static} + CREATE_NEW_SMARTTHING : int
            {static} + DELIVERY_VM : int
            {static} + DESCONNECT_ST_TO_SC : int
            {static} + MAKE_DECISION_MIGRATION : int
            {static} + NEXT_STEP : int
            {static} + NO_MIGRATION : int
            {static} + REMOVE_VM_OLD_CLOUDLET : int
            {static} + SET_MIG_STATUS_TRUE : int
            {static} + START_HANDOFF : int
            {static} + START_MIGRATION : int
            {static} + STOP_SIMULATION : int
            {static} + TO_MIGRATION : int
            {static} + UNLOCKED_HANDOFF : int
            {static} + UNLOCKED_MIGRATION : int
            {static} + VM_MIGRATE : int
        }
      }
    }
  }
  

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.Policies {
            {static} + ADD : int
            {static} + FIXED_AP_LOCATION : int
            {static} + FIXED_MIGRATION_POINT : int
            {static} + FIXED_SC_LOCATION : int
            {static} + ILP : int
            {static} + LIVE_MIGRATION : int
            {static} + LOWEST_DIST_BW_SMARTTING_AP : int
            {static} + LOWEST_DIST_BW_SMARTTING_SERVERCLOUDLET : int
            {static} + LOWEST_LATENCY : int
            {static} + MIGRATION_COMPLETE_VM : int
            {static} + MIGRATION_CONTAINER_VM : int
            {static} + RANDOM_AP_LOCATION : int
            {static} + RANDOM_SC_LOCATION : int
            {static} + REMOVE : int
            {static} + SPEED_MIGRATION_POINT : int
        }
      }
    }
  }
  

  namespace  {
    namespace rg.fog.vmmobile {
      namespace constants {
        class org.fog.vmmobile.constants.Services {
            {static} + HIBRID : int
            {static} + PRIVATE : int
            {static} + PUBLIC : int
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
