@startuml

title __POLICIES's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace example {
          namespace policies {
            class org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedLeastFullFirst {
                + VmAllocationPolicyCombinedLeastFullFirst()
                + allocateHostForVm()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace example {
          namespace policies {
            class org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst {
                # hostTotalBw : double
                # hostTotalMips : double
                # hostTotalPes : int
                # maxNumHostsUsed : int
                - freeBw : List<Long>
                - freeMips : List<Long>
                - freePes : List<Integer>
                - usedBw : Map<String, Long>
                - usedMips : Map<String, Long>
                - usedPes : Map<String, Integer>
                - vmTable : Map<String, Host>
                + VmAllocationPolicyCombinedMostFullFirst()
                + allocateHostForVm()
                + allocateHostForVm()
                + deallocateHostForVm()
                + getHost()
                + getHost()
                + getMaxNumHostsUsed()
                + getVmTable()
                + logMaxNumHostsUsed()
                + optimizeAllocation()
                # convertWeightedMetric()
                # getFreeBw()
                # getFreeMips()
                # getFreePes()
                # getUsedBw()
                # getUsedMips()
                # getUsedPes()
                # setFreeBw()
                # setFreeMips()
                # setFreePes()
                # setUsedBw()
                # setUsedMips()
                # setUsedPes()
                # setVmTable()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace example {
          namespace policies {
            class org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyMipsLeastFullFirst {
                + VmAllocationPolicyMipsLeastFullFirst()
                + allocateHostForVm()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace example {
          namespace policies {
            class org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyMipsMostFullFirst {
                + VmAllocationPolicyMipsMostFullFirst()
                + allocateHostForVm()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace sdn {
        namespace example {
          namespace policies {
            class org.cloudbus.cloudsim.sdn.example.policies.VmSchedulerTimeSharedEnergy {
                {static} - powerOffDuration : double
                - utilizationHistories : List<PowerUtilizationHistoryEntry>
                + VmSchedulerTimeSharedEnergy()
                + addUtilizationEntryTermination()
                + getUtilizationEnergyConsumption()
                + getUtilizationHisotry()
                # setAvailableMips()
                - addUtilizationEntry()
                - calculatePower()
                - getTotalMips()
            }
          }
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedLeastFullFirst -up-|> org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst
  org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst .up.|> org.cloudbus.cloudsim.sdn.power.PowerUtilizationMaxHostInterface
  org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst -up-|> org.cloudbus.cloudsim.VmAllocationPolicy
  org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyMipsLeastFullFirst -up-|> org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst
  org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyMipsMostFullFirst -up-|> org.cloudbus.cloudsim.sdn.example.policies.VmAllocationPolicyCombinedMostFullFirst
  org.cloudbus.cloudsim.sdn.example.policies.VmSchedulerTimeSharedEnergy .up.|> org.cloudbus.cloudsim.sdn.power.PowerUtilizationInterface
  org.cloudbus.cloudsim.sdn.example.policies.VmSchedulerTimeSharedEnergy -up-|> org.cloudbus.cloudsim.VmSchedulerTimeShared


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
