@startuml

title __DISTRIBUTIONS's Class Diagram__\n

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        interface org.cloudbus.cloudsim.distributions.ContinuousDistribution {
            {abstract} + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.ExponentialDistr {
            - mean : double
            - numGen : Random
            + ExponentialDistr()
            + ExponentialDistr()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.GammaDistr {
            - alpha : int
            - beta : double
            - numGen : Random
            + GammaDistr()
            + GammaDistr()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.LognormalDistr {
            - dev : double
            - mean : double
            - numGen : Random
            + LognormalDistr()
            + LognormalDistr()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.LomaxDistribution {
            - shift : double
            + LomaxDistribution()
            + LomaxDistribution()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.ParetoDistr {
            - location : double
            - numGen : Random
            - shape : double
            + ParetoDistr()
            + ParetoDistr()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.UniformDistr {
            - mag : double
            - min : double
            - numGen : Random
            + UniformDistr()
            + UniformDistr()
            + sample()
            {static} + sample()
            + setSeed()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.WeibullDistr {
            - alpha : double
            - beta : double
            - numGen : Random
            + WeibullDistr()
            + WeibullDistr()
            + sample()
        }
      }
    }
  }
  

  namespace  {
    namespace rg.cloudbus.cloudsim {
      namespace distributions {
        class org.cloudbus.cloudsim.distributions.ZipfDistr {
            - den : double
            - numGen : Random
            - shape : double
            + ZipfDistr()
            + ZipfDistr()
            + sample()
            - computeDen()
        }
      }
    }
  }
  

  org.cloudbus.cloudsim.distributions.ExponentialDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.GammaDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.LognormalDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.LomaxDistribution .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.LomaxDistribution -up-|> org.cloudbus.cloudsim.distributions.ParetoDistr
  org.cloudbus.cloudsim.distributions.ParetoDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.UniformDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.WeibullDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution
  org.cloudbus.cloudsim.distributions.ZipfDistr .up.|> org.cloudbus.cloudsim.distributions.ContinuousDistribution


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
